apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo
commonLabels:
  environment: qa

resources:
- deployment.yaml
- service.yaml
- ../shared

images:
- name: us-east1-docker.pkg.dev/dev-qmedia/boris-dev/demo-fgql-service
  newTag: 0.0.1

replacements:
  - path: ../shared/fgql-service-replacements.yaml
