apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    service: demo-service
    graph-url: http://demo.demo-service.svc.cluster.local:8080/graphql
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: api
  selector:
    app: demo-service